### ISSUE TITLE
Why would the new merit function value be larger than the old?

### ISSUE THREAD

**Issue by jhnsnshen** [Milad-Rakhsha/Interior-Point-Method#1]
Hello, your code is awesome and helps me a lot, but I have a question regarding the file "FindAlphas.m". 
Line 30 writes
if (merit_new>merit_old)
and if this condition is satisfied, the loop breaks. The book "Numerical Optimization" page 575, says to find the step lengths providing sufficient decrease of the merit function.
So, I was wondering why would the new merit function value be larger than the old one?
Looking forward to your reply. Thank you very much.

**Comment by Milad-Rakhsha** [comment]
I think that was just a safeguarding method to make sure that we are not picking an alpha value that results in increase in the merit function, 
That being said, I think I am not strictly following the "numerical optimization" book's algorithm in FindAlphas.m. Please let me know if you found a better way of choosing the step length
